### ISSUE TITLE
ModuleNotFoundError: No module named 'attention'

### ISSUE THREAD

**Issue by shouvik-paul** [xypan1232/iDeepA#2]
I am unable to run the code. I am facing this problem.
ModuleNotFoundError: No module named 'attention'.

**Comment by xypan1232** [comment]
Do you download the attention.py in the same directory? which can be imported when they are at the same directory.

**Comment by shouvik-paul** [comment]
Now it is successfully run on the  Linux (Ubuntu) Environment.

**Comment by Mirazul-Hoq** [comment]
> Do you download the attention.py in the same directory? which can be imported when they are at the same directory.

can you please give me the link to download attention.py??

**Comment by shouvik-paul** [comment]
> > Do you download the attention.py in the same directory? which can be imported when they are at the same directory.
> 
> can you please give me the link to download attention.py??

you can easily download the file from this repository(code). anyhow the link is ' https://github.com/xypan1232/iDeepA '
download the zip file. I suggest you to run it on the Linux Environment.

**Comment by Mirazul-Hoq** [comment]
Thank you for your email.
I don't have linux environment right now. Will it cause any problem if I
run it on windows??

**Comment by xypan1232** [comment]
We only tested it in the Linux enviroment.
